//
//  crs-ios-Bridging-Header.h
//  crs-ios
//
//  Created by Brian Osborn on 07/12/21.
//  Copyright © 2021 NGA. All rights reserved.
//

#ifndef crs_ios_Bridging_Header_h
#define crs_ios_Bridging_Header_h

#import "crs_ios.h"
#import "CRSCategoryTypes.h"
#import "CRSCommon.h"
#import "CRSCompoundCoordinateReferenceSystem.h"
#import "CRSCoordinateReferenceSystem.h"
#import "CRSObject.h"
#import "CRSSimpleCoordinateReferenceSystem.h"
#import "CRSTypes.h"
#import "CRSAbridgedCoordinateTransformation.h"
#import "CRSBoundCoordinateReferenceSystem.h"
#import "CRSAxis.h"
#import "CRSAxisDirectionTypes.h"
#import "CRSCoordinateSystem.h"
#import "CRSCoordinateSystemTypes.h"
#import "CRSDateTime.h"
#import "CRSDatumEnsemble.h"
#import "CRSDatumEnsembleMember.h"
#import "CRSDynamic.h"
#import "CRSExtent.h"
#import "CRSGeographicBoundingBox.h"
#import "CRSIdentifiable.h"
#import "CRSIdentifier.h"
#import "CRSReferenceFrame.h"
#import "CRSScopeExtentIdentifierRemark.h"
#import "CRSTemporalExtent.h"
#import "CRSUnit.h"
#import "CRSUnitTypes.h"
#import "CRSUnits.h"
#import "CRSUsage.h"
#import "CRSVerticalExtent.h"
#import "CRSDerivedCoordinateReferenceSystem.h"
#import "CRSDerivingConversion.h"
#import "CRSEngineeringCoordinateReferenceSystem.h"
#import "CRSEngineeringDatum.h"
#import "CRSEllipsoid.h"
#import "CRSEllipsoidTypes.h"
#import "CRSEllipsoids.h"
#import "CRSGeoCoordinateReferenceSystem.h"
#import "CRSGeoDatum.h"
#import "CRSGeoDatums.h"
#import "CRSGeoDatumEnsemble.h"
#import "CRSGeoReferenceFrame.h"
#import "CRSPrimeMeridian.h"
#import "CRSPrimeMeridians.h"
#import "CRSTriaxialEllipsoid.h"
#import "CRSCoordinateMetadata.h"
#import "CRSCommonOperation.h"
#import "CRSConcatenatedOperation.h"
#import "CRSCoordinateOperation.h"
#import "CRSOperation.h"
#import "CRSOperationMethod.h"
#import "CRSOperationMethods.h"
#import "CRSOperationParameter.h"
#import "CRSOperationParameters.h"
#import "CRSOperationTypes.h"
#import "CRSPointMotionOperation.h"
#import "CRSSimpleOperation.h"
#import "CRSParametricCoordinateReferenceSystem.h"
#import "CRSParametricDatum.h"
#import "CRSMapProjection.h"
#import "CRSProjectedCoordinateReferenceSystem.h"
#import "CRSTemporalCoordinateReferenceSystem.h"
#import "CRSTemporalDatum.h"
#import "CRSVerticalCoordinateReferenceSystem.h"
#import "CRSVerticalDatumEnsemble.h"
#import "CRSVerticalReferenceFrame.h"
#import "CRSKeyword.h"
#import "CRSReader.h"
#import "CRSTextConstants.h"
#import "CRSTextReader.h"
#import "CRSTextUtils.h"
#import "CRSWriter.h"
#import "CRSProjConstants.h"
#import "CRSProjParams.h"
#import "CRSProjParser.h"

#endif /* crs_ios_Bridging_Header_h */
